#image: python:latest

stages:
   - code_test
   - code_release
   - code_deploy

# test du code
code_test:
  stage: code_test
  tags:
   - gitlab
  script:
   - python -m unittest discover
   - echo "Test du code effectué"

#Archive
code_release:
   stage: code_release
   tags:
      - gitlab
   script:
    - zip lambda_function.zip index.py
    - echo "Archive"

#Deployer
code_deploy:
   stage: code_deploy
   tags:
      - gitlab
   script:
    - export AWS_ACCESS_KEY_ID=AKIA2G2XJY5PWFSNRXVS
    - export AWS_SECRET_ACCESS_KEY=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
    - aws s3 cp lambda_function.zip s3://gitlab-examen-d3/
    - aws lambda update-function-code --function-name gitlab-examen-d3 --s3-bucket gitlab-examen-d3 --s3-key lambda_function.zip
    - git checkout dev
    - git rebase master


