#image: python:latest

stages:
   - code_test
   - code_release
   - code_deploy

# test du code
code_test:
  stage: code_test
  tags:
   - gitlab
  script:
   - python -m unittest discover
   - echo "Test du code effectué"

#Archive
code_release:
   stage: code_release
   tags:
      - gitlab
   script:
    - apt-get install zip unzip
    - zip lambda_function.zip index.py
    - echo "Archive"

#Deployer
code_deploy:
   stage: code_deploy
   tags:
      - gitlab
   script:
    - aws s3 cp lambda_function.zip s3://gitlab-examen-group_id=3/
    - aws lamda update-function-code --function-name gitlab-examen-group_id=3 --s3-bucket gitlab-examen-group_id=3 --s3-key lambda_function.zip
   
    # only:
    #  - master
